services:
  - type: web
    name: docassist-backend
    env: python
    runtime: python3.8.0
    buildCommand: |
      # Update package list and install system dependencies
      apt-get update
      apt-get install -y gfortran gcc g++ make python3-dev libblas-dev liblapack-dev libatlas-base-dev
      apt-get install -y python3-scipy python3-numpy python3-pandas
      export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
      export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      # Upgrade pip first
      python -m pip install --upgrade pip
      # Install build tools
      pip install --no-cache-dir setuptools wheel
      # Install numpy first
      pip install --no-cache-dir numpy==1.21.6
      # Install scipy using system libraries
      pip install --no-cache-dir scipy==1.7.1 --no-build-isolation
      # Install pandas separately
      pip install --no-cache-dir pandas==1.3.0
      # Install remaining requirements
      pip install -r requirements.txt
      # Ensure model directories exist
      mkdir -p backend/models
      # Copy model file to both possible locations
      cp models/final_model_pipeline.pkl backend/models/
      # Print debug information
      echo "Model file location check:"
      ls -l models/
      ls -l backend/models/
      # Copy app.py to the root directory
      cp backend/app.py .
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: NPY_NUM_BUILD_JOBS
        value: "4"
      - key: MODEL_PATH
        value: "models/final_model_pipeline.pkl"
      - key: PYTHONPATH
        value: "." 