services:
  - type: web
    name: docassist-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y gfortran
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production 